### ISSUE TITLE
[문의] 0.13 버전의 모델크기는 base만 제공하나요?

### ISSUE THREAD

**Issue by mrchypark** [bab2min/Kiwi#108]
확인차 이슈 생성합니다. 

감사합니다.

**Comment by bab2min** [comment]
@mrchypark
모델 크기 차이 대비 성능 차이가 그렇게 크지도 않고, 다른 모델 사이즈를 이용하는 경우도 적은거 같아, 다른 사이즈를 튜닝하는 데 들이는 리소스 대비 아웃풋이 적은 듯하여 고민 중에 있습니다. 그래서 일단은 base 크기 위주로 배포하며 좀 더 상황을 살펴보고자 해요.

**Comment by mrchypark** [comment]
알겠습니다. 우선 base만 있는 것으로 이해하고, 이슈 종료하겠습니다. 답변주셔서 감사합니다. @bab2min
