### ISSUE TITLE
[제안] 릴리즈 압축에 헤더가 포함되어 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by mrchypark** [bab2min/Kiwi#110]
```
include
lib
```
같은 폴더 형태로 구성되어 있으면 사용하는데 편리할 것 같습니다.

**Comment by bab2min** [comment]
@mrchypark 좋은 제안 감사합니다~
맞네요. 그렇게 제공하는게 사용하기에 편하겠네요. 다음 버전부터는 릴리즈 파일 구조를 위와 같이 고치도록 할게요!
