### ISSUE TITLE
하나의 문장에서 아무 단어도 분류되지 않는 경우

### ISSUE THREAD

**Issue by Rhyankwon** [bab2min/Kiwi#114]
현재 키위 형태소 분석기를 사용해 스팸메세지의 키워드를 추출하는 작업을 진행 중입니다.
항상 잘 사용중이고 개발자분께 감사드립니다.

현재 한글만 추출해서 띄어쓰기를 모두 없앤 후 명사를 추출하는 방식으로 사용중이고 대부분의 경우 정상적으로 매우 잘, 명사를 추출합니다.

그런데 일부 문장의 경우에서 아예 아무런 단어도 추출하지 못한채  NNG의 명사 하나만 추출하는 현상을 확인했습니다.

다음의 문장이 그 예시입니다.

발신광고갑자기연락드려죄송합니다국내규모가장큰세력이며만구독자를보유하고있고주식유튜버입니다무조건큰돈버는세력

위 문장을 tokenize하면 NNG 형태소 하나가 추출됩니다.

위 경우에서는 주식유튜버 앞에 띄어쓰기를 하면 정상적으로 단어들이 추출됩니다.

저와 같은 케이스인 분이 있는지, 그런 경우 어떻게 해결했는지 궁금합니다.

**Comment by bab2min** [comment]
안녕하세요 @Rhyankwon 
제보해주신 내용은 형태소 분석기의 오류로 보이는데요,
정확한 원인에 대해서는 조금 더 조사해보도록 하겠습니다.

**Comment by Rhyankwon** [comment]
감사합니다 :) 일단은 띄어쓰기가 돼있는 원본 텍스트에서 형태소 추출 진행했습니다.

**Comment by bab2min** [comment]
@Rhyankwon 
안녕하세요~ 해당 문제는 사전에 등록되어 있지 않는 문자열 패턴이 연속하여 등장하는 경우에 발생하는 것으로 확인되었으며, 12월 24일 배포된 0.14.1버전에서 수정되었습니다.
참고로 0.14.1버전에서는 다음과 같이 분석됩니다.
`발신/NNG 광고/NNG 갑자기/MAG 연락/NNG 드리/VV 어/EC 죄송하/VA ᆸ니다/EF 국내/NNG 규모/NNG 가장/MAG 크/VA ᆫ/ETM 세력/NNG 이/VCP 며/EC 만/JX 구독자/NNG 를/JKO 보유/NNG 하/XSV 고/EC 있/VX 고/EC 주식/NNG 유/NNG 튜/NNG 버/NNP 이/VCP ᆸ니다/EF 무조건/MAG 크/VA ᆫ/ETM 돈/NNG 벌/VV 는/ETM 세력/NNG`
