### ISSUE TITLE
[제안] Normalized F1 score

### ISSUE THREAD

**Issue by hyunwoongko** [bab2min/Kiwi#118]
Kss와 Kiwi의 문장분리 성능을 평가하면서 EM score와 F1 score의 각각 단점을 분석하고 이를 보완하는 새로운 메트릭인 Normalized F1 score라는 평가 메트릭을 개발하였습니다.

자세한 내용은 아래에서 확인하실 수 있습니다.
https://github.com/hyunwoongko/kss/blob/main/README.md#4-consideration-of-metrics-and-normalized-f1-score

Kiwi 레포지토리에서도 문장분리 성능 평가용으로 이 메트릭을 도입해보시면 어떨까 하여 소개차 공유드립니다. :)

**Comment by bab2min** [comment]
안녕하세요 @hyunwoongko 님
좋은 제안 감사합니다. 그런데 해당 README.md 파일에 `4-consideration-of-metrics-and-normalized-f1-score` 단락이 없는 거 같네요~ 확인해주시면 살펴보고 Kiwi 평가에도 반영해보도록 하겠습니다.

**Comment by hyunwoongko** [comment]
아마 접어둔 상태라서 바로 거기로 안당겨질거에요.
Performance Analysis 파트 눌러보시면 보이실겁니다.
