### ISSUE TITLE
reading type 'char16_t' failed: iostream stream error

### ISSUE THREAD

**Issue by tree1891** [bab2min/Kiwi#119]
kiwi_win_x64_v0.14.1 의 kiwi-test.exe 를 실행했는데 아래와 같은 오류가 발생합니다.
`unknown file: error: C++ exception with description "reading type 'char16_t' failed: iostream stream error" thrown in the test body.`

**Comment by bab2min** [comment]
@tree1891 안녕하세요, 해당 문제는 모델 파일을 읽지 못해서 발생하는 것으로 보이는데요,
`kiwi-test`는 현재 실행 경로에서 `./ModelGenerator` 위치에 모델 파일이 존재할걸 가정하고 작동합니다.
모델 파일을 받으셔서 그 위치에 넣으시고 재실행해보시길 권장드립니다~

**Comment by tree1891** [comment]
해당 폴더는 이미 있습니다. 모델 파일이 없는 경우에는 해당 메시지가 나오는것을 확인했습니다.

**Comment by bab2min** [comment]
@tree1891 ,
아 그렇군요. 그러면 모델 파일 버전이 안 맞는걸 수 있습니다. Kiwi 0.14.x 바이너리는 0.14.x버전의 모델 파일하고만 호환이 됩니다.

**Comment by tree1891** [comment]
바이너리 릴리즈에는 모델파일이 없어서 ModelGenerator 폴더는 소스 레포지토리에서 다운했습니다.

**Comment by bab2min** [comment]
https://github.com/bab2min/Kiwi/releases/tag/v0.14.1 여기 보시면 [kiwi_model_v0.14.1_base.tgz](https://github.com/bab2min/Kiwi/releases/download/v0.14.1/kiwi_model_v0.14.1_base.tgz) 이라는 이름으로 모델이 올라가 있습니다. 이걸 받아서 사용하시면 됩니다~

**Comment by tree1891** [comment]
정상동작 하는것 같습니다. 감사합니다.

**Comment by CharlesKwonOhjun** [comment]
저의 해결책을 공유 드립니다. 
kiwigui의 모델로 교체하니 아무 문제 없이 작동됩니다. 해당 binary을 다운 받아 kiwi git의 기본 배포 모델을 교체하는 방법으로 해결했습니다. 감사합니다.
