### ISSUE TITLE
[바이너리] 문장분리 방법

### ISSUE THREAD

**Issue by tree1891** [bab2min/Kiwi#120]
바이너리 릴리즈로 문장분리를 할수 없는가요?

**Comment by bab2min** [comment]
@tree1891 네 현재 제공되는 실행 파일들은 최소한의 예제들이라고 보시면 되구요,
실제 사용은 Kiwi를 library로 사용하여 코드를 작성해 쓰는걸 가정하고 있습니다.
다만 문장 분리용 바이너리가 제공되면 더욱 편리할 듯하니 다음 번 업데이트에 자동 빌드 절차에 문장 분리 바이너리도 추가하도록 하겠습니다.
그 전까지는 Python용 패키지인 https://github.com/bab2min/kiwipiepy 를 사용하여 문장 분리를 하는걸 추천드립니다.
