### ISSUE TITLE
kiwi_builder_load_dict의 인자 설명에 관해

### ISSUE THREAD

**Issue by CharlesKwonOhjun** [bab2min/Kiwi#124]
kiwi_builder_load_dict가 설명대로 작동이 안되어 실제 호출되는 소스를 보니 사전파일 경로가
Kiwi_builder_init의 mode_path와 같이 경로명만 저정하는 것이 아니라 파일명까지 지정해야 작동되는 코드로 되어 있습니다.

 @param dict_path 사전 파일 경로. 라고 되어 있는 부분에
dict_file이나 사전파일명 으로 변경하면 명확하지 않을까 하는 소견입니다.

감사합니다.

/**
 * @brief 사용자 사전으로부터 단어를 읽어들입니다.
 * 
 * @param handle KiwiBuilder의 핸들.
 * @param dict_path 사전 파일 경로.
 * @return 추가된 단어 수.
 */
DECL_DLL int kiwi_builder_load_dict(kiwi_builder_h handle, const char* dict_path);

**Comment by bab2min** [comment]
@CharlesKwonOhjun 문서화가 빈약한 부분이 있어서 다소 혼란스러우셨겠네요~ 좋은 제안 감사드리며, 반영하도록 하겠습니다.
