### ISSUE TITLE
URL 및 이메일 주소, #해시태그 분석 기능 추가

### ISSUE THREAD

**Issue by bab2min** [bab2min/Kiwi#14]
현재는 URL이나 이메일 주소, #해시 태그 등을 입력하면 모두 알파벳, 특수 문자 등으로 분리하여 태깅하는데 이를 묶어서 분석해내는 기능이 있으면 좋을듯

제안 태그
* W_URL : 웹 URL 주소 (예시: http://abc.com/def/?a=b )
* W_EMAIL: 이메일 주소 (예시: abc@def.com )
* W_HASHTAG: 해시 태그 (예시: #해시_태그 )

**Comment by bab2min** [comment]
0.8.0 버전에서 추가완료

**Comment by SHwan93** [comment]
#해시태그와 마찬가지고 @link 기능은 추가 할 계획이 있으신가요?

**Comment by bab2min** [comment]
@SHwan93  좋은 의견 감사합니다. 다음 업데이트 때 @로 시작하는 link를 분석하는 기능을 추가해보도록 하겠습니다.

**Comment by bab2min** [comment]
@link 정규식 패턴은 `@[-_a-zA-Z0-9.]+` 정도로 하면 될듯.

**Comment by SHwan93** [comment]
위처럼하면 abcd@google.com에도 걸리는데 

문제가 되지 않는다면 이메일에대한 태그도 만들어서 이메일 먼저 거르고 해시태그를 찾는것은 어떨까요?
