### ISSUE TITLE
품사 태그 관련 문의

### ISSUE THREAD

**Issue by sgs8010** [bab2min/Kiwi#149]
안녕하세요. 
항상 프로그램을 잘 활용하고 있습니다. 감사하다는 인사 먼저 드립니다.
궁금한 것은 품사 태그 관련인데요, 
형용사 VA와 VA-I의 구분 기준, 차이점이 궁금하여 문의드립니다.  
XSA-I, VV-I    , VV-R과 같은 I   , R의 기준도 궁금합니다..!

**Comment by bab2min** [comment]
안녕하세요 @sgs8010 
용언류 뒤에 붙는 `-I`, `-R`는 해당 용언의 불규칙 활용여부를 나타내는 표지입니다. `-I`가 불규칙(Irregular) `-R`이 규칙(Regular) 활용을 뜻합니다. 일반적으로 대부분의 용언은 그 형태만 보면 규칙인지 불규칙인지 알 수 있으나, 일부는 규칙 활용과 불규칙 활용이 동일하여 형태만 보고서는 구분할 수 없습니다. 이 경우를 가려내기 위해 `-I`, `-R`표지를 붙입니다.

예를 들어 동사 `먹다`는 규칙 활용을 하므로 `VV-R`이지만 항상 규칙 활용이므로 Kiwi에서는 굳이 별도로 `-R`을 붙이지 않고 생략하여 `먹/VV`라고 씁니다. 그러나 `묻다`의 경우 `묻다/물어/물으니`와 같이 불규칙 활용을 하는 동사와 `묻다/묻어/묻으니`와 같이 규칙 활용을 하는 동사가 같은 형태로 존재합니다. 따라서 Kiwi에서는 전자는 `묻/VV-I`으로, 후자는 `묻/VV-R`으로 표기하여 둘을 구분하여 줍니다. 형용사를 비롯한 나머지 용언에 대해서도 마찬가지입니다.
