### ISSUE TITLE
[오류] 같은 단어에 대한 형태소 분석 문제

### ISSUE THREAD

**Issue by aajik** [bab2min/Kiwi#161]
안녕하세요.
Python 3.10.12, Kiwi.version:0.17.1을 사용하고 있습니다.

문장 예시)
1) 자녀도 같이 해야하는데, 자녀가 **미성년자**에요 어떻게 하나요?
2) **미성년자** 해외여행 신청 방법은 어떻게 되나요?

위 두 문장을 아래와 같이 형태소 분석을하면
2)번 문장은 **미성년자**를 잘 분리해주고 있습니다.
tokens = kiwi.tokenize("미성년자 해외여행 신청 방법은 어떻게 되나요?", normalize_coda=True)
[Token(form='미성년자', tag='NNG', .....]

1)번 문장 **미성년자**를 분리하지 못하고 있습니다.
tokens = kiwi.tokenize("자녀도 같이 해야하는데, 자녀가 미성년자에요 어떻게 하나요?", normalize_coda=True)
[Token(form='자녀',.., Token(form='미', tag='XPN', start=18, len=1), Token(form='성년자', tag='NNG']

위 1)번을  "미성년자"로 분리가 안되는 문제가 있습니다. 해결 방법이 있을까요.
감사합니다.

**Comment by bab2min** [comment]
안녕하세요~ @aajik 
kiwipiepy discussion쪽에도 질문을 남기셨더라구요~ 그쪽에 답변해드렸습니다.
https://github.com/bab2min/kiwipiepy/discussions/163
