### ISSUE TITLE
혹시 javascript용 API wrapper 개발 계획이 있을까요?

### ISSUE THREAD

**Issue by calycekr** [bab2min/Kiwi#169]
node.js 단에서 바로 사용하고 싶은데, 혹시 계획이 있으신지 궁금합니다.

**Comment by bab2min** [comment]
안녕하세요 @calycekr , 먼저 Kiwi에 대한 관심에 감사드립니다~
찾아보니 node.js에서 C++코드를 addon으로 붙이는 방법이 있어서 기술적으로는 충분히 가능한 계획으로 보입니다~ (https://nodejs.org/api/addons.html#c-addons)
그런데 안타깝지만 제가 node.js 관련해서는 아는 바가 적다보니 이에 대해 wrapper를 개발할 계획은 없는 상황입니다. node.js addon 개발 경험이 있으신 분들의 기여를 기다리고 있겠습니다.

**Comment by bab2min** [comment]
@calycekr 
#171 이 반영된 0.18.0 버전을 배포했습니다. js용 wrapper에 대해서는 [binding/wasm](https://github.com/bab2min/Kiwi/tree/v0.18.0/bindings/wasm)를 참조해주시길 바랍니다.
