### ISSUE TITLE
인용부호 열림 (SSO) 태그가 앞 문장 뒤에 붙는 문제

### ISSUE THREAD

**Issue by hkhpub** [bab2min/Kiwi#181]
인용부호 열림 (SSO)태그가 다음과 같이 앞 문장에 붙는 문제가 발생합니다.
```
from kiwipiepy import Kiwi
kiwi = Kiwi()
s = "존 슈발John Schwall은 그에 꼭 들어맞는 흥미로운 사례였다. 슈발의 아버지와 할아버지는 스테이튼 아일랜드의 소방관이었다. “제 친가 쪽의 남자들은 모두 소방관이에요. 전 다 른 일을 하고 싶었죠.” 슈발이 말했다."
sents = kiwi.split_into_sents(s, return_tokens=True)
for sent in sents:
    print(sent.text)
```

> Output:
> 존 슈발John Schwall은 그에 꼭 들어맞는 흥미로운 사례였다.
> **슈발의 아버지와 할아버지는 스테이튼 아일랜드의 소방관이었다. “**
> 제 친가 쪽의 남자들은 모두 소방관이에요.
> **전 다른 일을 하고 싶었죠.”**
> 슈발이 말했다.
> 

해결 방법이 있을까요?

**Comment by bab2min** [comment]
@hkhpub 님 오류 제보 감사드립니다~
해당 문제는 문장 분리 로직의 버그로 확인되었으며, 수정되어 다음 업데이트 때에 해결될 예정입니다!

**Comment by bab2min** [comment]
@hkhpub 님, 제보해주신 오류는 0.18.1버전에서 수정되었습니다~ 다시 한 번 오류 제보에 감사드립니다.

**Comment by hkhpub** [comment]
감사합니다!
