### ISSUE TITLE
사용자 사전 관련 문의드립니다.

### ISSUE THREAD

**Issue by UESENPAI** [bab2min/Kiwi#196]
먼저 좋은 형태소 분석기 제공해주셔서 감사드립니다.

사용자 사전 형식이

세카이가유메미루유메노나카/사이슈미라이오미세테!	NNP	-144.2184

이렇게 되어있던데

저렇게 추가하면 뛰어쓰기 적용한 단어에도 적용이 되는걸까요

예를 들어서 경상북도립영천금호공공도서관 이면

경상북도 도립 영천 금호 공공 도서관이라는 뛰어쓰기 한 단어를 사용자 사전에 등록하지 않아도 동일하게 취급하나요?

엠베딩해서 보관하는게 아니라서 잘 잡히나 궁금해서 여쭤보고요

또 정규식처럼 특정 접두사나 접미사가 포함된 단어도 취급이 가능한지 여쭤볼게요

예를들어서 질산나트륨 수산화나트륨 염화나트륨 탄산나트륨 중탄산나트륨등

~륨으로 끝나는 단어는 NNP로 넣고 싶다고 할때 따로 제공하는 정규식 문법이 있을까요?

파이썬 문서화와 제공해주신 기본 제공 유저 데이터 사전을 봤는데 딱히 없어서 여쭤봅니다

MeCab같은경우 XXXX륨 해서 넣는식으로 처리하는데 KIWI에서는 제공이 될까요?

긴 질문 읽어주셔서 감사드립니다

**Comment by bab2min** [comment]
안녕하세요 @UESENPAI 
사용자 단어의 공백 규칙은 1) 원형에 공백이 없는 경우 원칙상 공백이 없는 형태하고만 일치. 2) 원형에 공백이 있는 경우는 동일한 위치에 공백이 있는 경우 혹은 공백 없이 이어쓴 형태하고만 일치합니다. Python 코드로 공백 있는 케이스의 예제를 들자면 다음과 같습니다. (예시에서는 `add_user_word`를 사용하고 있지만 `user_dictionary`에서도 동일한 규칙이 적용됩니다.)

```python
>>> kiwi.add_user_word('대학생 선교회', 'NNP')
True

# 등록한 것과 동일한 형태에서는
# 당연히 잘 분석됩니다.
>>> kiwi.tokenize('대학생 선교회에서') 
[Token(form='대학생 선교회', tag='NNP', start=0, len=7),
 Token(form='에서', tag='JKB', start=7, len=2)]

# 추가로 공백이 없는 형태에도 일치가 가능합니다.
>>> kiwi.tokenize('대학생선교회에서') 
kiwi.tokenize('대학생선교회에서')  
[Token(form='대학생 선교회', tag='NNP', start=0, len=6),
 Token(form='에서', tag='JKB', start=6, len=2)]

# 탭 문자나 줄바꿈 문자 등이 들어가도 일치가 가능합니다.
# 연속한 공백 문자는 공백 1번과 동일하게 처리합니다.
>>> kiwi.tokenize('대학생 \t \n 선교회에서') 
[Token(form='대학생 선교회', tag='NNP', start=0, len=11),
 Token(form='에서', tag='JKB', start=11, len=2)]

# 그러나 사전 등재 시 공백이 없던 지점에
# 공백이 있는 경우에는 일치가 불가능합니다.
>>> kiwi.tokenize('대학 생선 교회에서')      
[Token(form='대학', tag='NNG', start=0, len=2),
 Token(form='생선', tag='NNG', start=3, len=2),
 Token(form='교회', tag='NNG', start=6, len=2),
 Token(form='에서', tag='JKB', start=8, len=2)]

# space_tolerance를 2로 설정하여
# 공백이 두 개까지 틀린 경우를 허용하도록 하면
# '대학 생선 교회'에도 '대학생 선교회'가 일치하게 됩니다.
>>> kiwi.space_tolerance = 2
>>> kiwi.tokenize('대학 생선 교회에서')
[Token(form='대학생 선교회', tag='NNP', start=0, len=8),
 Token(form='에서', tag='JKB', start=8, len=2)]
```

정규식이나 비슷한 문법으로 특정 접두사/접미사를 일괄 지정하는 기능은 user dictionary 자체에는 아직 없습니다. 대신 Python wrapper에서는 [`add_re_word`라는 메소드](https://bab2min.github.io/kiwipiepy/v0.19.1/kr/#kiwipiepy.Kiwi.add_re_word)를 통해 정규식으로 단어를 일괄적으로 등록하는 기능을 제공하고 있으니 이걸 사용하는걸 권장해드립니다.

**Comment by UESENPAI** [comment]
와 친절한 설명 감사드립니다.

바로 이해했습니다.

좋은하루되세요
