### ISSUE TITLE
kiwi R package 제안

### ISSUE THREAD

**Issue by mrchypark** [bab2min/Kiwi#21]
안녕하세요, 소중한 패키지 제작해 주셔서 정말 감사드립니다.

다름이 아니라 kiwi를 R 패키지화 하는 작업을 진행하고 있는데요.
혹시 제가 계속 제작해서 제공해도 괜찮을지 문의드리려고 합니다.

https://github.com/mrchypark/Elbird

다시 한 번 좋은 패키지 제작해주셔서 대단히 감사드립니다.

**Comment by bab2min** [comment]
오, 멋진 wrapper를 작성해주셔서 감사합니다. 덕분에 R유저들도 편하게 사용할 수 있겠네요. 메인 README에서도 소개하도록 하겠습니다.
R쪽은 잘 몰라서 큰 도움은 못되겠지만, 작업 도중 도움이 필요한 부분있으면 편하게 요청주세요.
다시 한 번 감사합니다.
