### ISSUE TITLE
구두점 없는 긴 텍스트 분할하여 처리하기

### ISSUE THREAD

**Issue by bab2min** [bab2min/Kiwi#22]
현재 분석기 알고리즘 상 입력 텍스트가 길수록 속도가 느려지고 정확도도 떨어지는 한계가 있음. 
이를 회피하기 위해 마침표를 기준으로 입력 텍스트를 분할하여 여러 단위로 각각 분석을 실시한 뒤 다시 결합하는 방식을 사용중.
그러나 일부 웹 텍스트의 경우 명시적으로 마침표를 사용하지 않고 문장을 길게 잇는 경우도 있어 분석 정확도가 크게 손실되는 문제가 있음.
이에 다음과 같은 개선 방안을 제안

1. 간단한 규칙기반 문장 분리기를 사용하여 빠르게 텍스트를 분할하기
2. 전이 그래프에서 노드가 한 곳으로 모이는 지점을 찾아내어 해당 지점 전후로 동적으로 그래프 분할하기

**Comment by junuMoon** [comment]
이슈를 보고 관심이 있어 질문드립니다.
룰기반 분리기 적용 후 2번 계획에 대해 설명해주실 수 있으신가요?

**Comment by tree1891** [comment]
아직 구현중이신가요?

**Comment by bab2min** [comment]
뒤 늦은 문서화이긴 하지만, PR #128 에서 `전체 입력에 대해 문장 분할` -> `패턴 추출` -> `형태소 분석 순서`로 진행하던 구조에서 `패턴 추출 과정에서 청크 분할` -> `분할된 청크에 대해서 형태소 분석` -> `이후 지점부터 패턴 추출 재개`와 같은 구조로 변경했기 때문에 해당 기능이 굳이 필요 없어졌습니다.
