### ISSUE TITLE
형태소 분석 결과에 어절 번호 추가

### ISSUE THREAD

**Issue by bab2min** [bab2min/Kiwi#31]
현재는 분석 결과가 형태, 품사태그, 시작 위치, 끝 위치 정보만 담고 있는데, 추가적으로 어절 번호를 함께 부착해주면 유용한 경우가 있어 보임
(관련 이슈: https://github.com/bab2min/kiwi-gui/issues/4 )

**Comment by bab2min** [comment]
현재 형태소 분석 결과는 다음과 같은 `TokenInfo` 타입에 담겨서 반환된다.

https://github.com/bab2min/Kiwi/blob/de7201c02ed95ed4d44c168dc7f51b9c6ad58590/include/kiwi/Types.h#L159-L166

여기서 어절 번호용 멤버 변수 `wordPosition`를 추가하고 반환 시에 이 값을 추가로 채워주도록 하면 구현 가능.

어절 번호는 0번부터 시작해 띄어쓰기로 단어가 분절될때마다 1씩 증가. 
어절 번호 예시:
```text
아버지가 방에 들어가신다.

"형태소^어절번호/품사태그" 형태로 표기
아버지^0/NNG  가^0/JKS  방^1/NNG  에^1/JKB  들어가^2/VV  시^2/EP  ㄴ다^2/EF
```

`TokenInfo`에 값을 채워넣는 부분은 `Kiwi::analyzeSent` 함수의 다음 부분에서 수행된다:
https://github.com/bab2min/Kiwi/blob/de7201c02ed95ed4d44c168dc7f51b9c6ad58590/src/Kiwi.cpp#L589-L596

그러나 이 부분에서는 입력이 이미 형태소 단위로 분리되어 원본의 공백 여부를 파악할 수 없으므로 다음과 같이 시작부분에서 미리 문자 위치당 어절번호를 파악하는게 좋아보인다:
https://github.com/bab2min/Kiwi/blob/de7201c02ed95ed4d44c168dc7f51b9c6ad58590/src/Kiwi.cpp#L522-L529
`posMap`은 각 문자별 position위치를 담는 변수인데, 여기에 값을 채워넣는 것과 유사하게 `wordPositionMap`을 변수를 선언하고 그 안에 값을 채워넣으면 될듯.

**Comment by emiatej9** [comment]
@bab2min 
아직 아무도 가져가지 않았으니, 제가 맡아서 해보도록 하겠습니다 ㅎㅎ
