### ISSUE TITLE
googletest에서 cmake deprecation warning 발생

### ISSUE THREAD

**Issue by emiatej9** [bab2min/Kiwi#34]
현재 cmake 3.19.2 버전을 사용하고 있는데 `cmake -DCMAKE_BUILD_TYPE=Release ../` 명령 실행 시에 다음과 같은 deprecation waring 이 발생합니다.

```
CMake Deprecation Warning at third_party/googletest/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

googletest에서 발생하는 것으로 보이는데, googletest에서는  [Bump CMake minimum to 2.8.12](https://github.com/google/googletest/pull/3094) 에서 해당 이슈가 해결되었고, [v1.11.0](https://github.com/google/googletest/releases/tag/release-1.11.0) 에 반영되어있습니다.

현재 서브모듈로 포함되어있는 googletest 는 v1.8.x 네요. googletest 버전을 올려되 되지 않을까 합니다.

**Comment by bab2min** [comment]
@emiatej9 
좋은 제안 감사합니다. warning 메세지가 뜨는걸 확인 못했었는데요, 큰 문제 없다면 googletest 버전을 올리는게 좋겠네요!
혹시 @emiatej9 님께 이슈 해결 부탁드려도 될까요?

**Comment by emiatej9** [comment]
@bab2min 네, 알겠습니다. 한 번 도전해 보겠습니다 🙆‍♂️
