### ISSUE TITLE
Light 버전 모델 지원 문의

### ISSUE THREAD

**Issue by patnh2** [bab2min/Kiwi#48]
좋은 프로젝트 공유해 주셔서 감사합니다!
KNLM 파일이 약 50MB 정도 되는데요.
혹시 지금보다 더 경량화한 버전의 모델을 지원하실 계획은 없는지 궁금합니다.
감사합니다^^

**Comment by bab2min** [comment]
안녕하세요 @patnh2, 좋은 의견 주셔서 감사합니다~
사실 현재 압축된 KNLM 포맷을 사용하는 기능이 Kiwi내부에 구현되어 있습니다만, 이 경우 압축을 해제하고 모델을 메모리에 적재하는데 시간이 좀 더 걸리는 문제가 있어서 default로는 사용하지 않도록 해두었습니다. 이렇게 압축된 KNLM포맷을 쓴다해도 용량이 30MB~40MB 정도라서 zip으로 압축하는것보다 크기도 하구요.

정확도를 조금 잃어도 된다면 모델 용량을 줄이는게 가능한데, 혹시 어느 정도 크기를 원하시나요? 요청하시는 사이즈에 맞춰 모델을 만들어보고 정확도 테스트를 해보도록 할게요ㅎㅎ

**Comment by patnh2** [comment]
답변 감사합니다.
온디바이스쪽에 관심이 있어서 문의 드렸습니다.
정확도를 희생하더라도 지금보다 1/2 또는 1/4 정도 모델 경량화가 가능할까요? ^^;
감사합니다!

**Comment by bab2min** [comment]
@patnh2 

저빈도 long tail을 일부 잘라서 모델 크기를 줄여보는 테스트를 해봤습니다~
<table>
<tr><th></th><th>M(원 모델)</th><th>S</th><th>XS</th></tr>
<tr><th>knlm 크기 (MB)</th><td>48.3</td><td>14.2</td><td>8.3</td></tr>
<tr><th>web.txt</th><td>82.28</td><td>82.49</td><td>82.19</td></tr>
<tr><th>written.txt</th><td>94.68</td><td>94.68</td><td>94.96</td></tr>
<tr><th>written01.txt</th><td>91.21</td><td>89.61</td><td>89.20</td></tr>
<tr><th>written02.txt</th><td>94.87</td><td>93.53</td><td>93.03</td></tr>
<tr><th>written03.txt</th><td>96.30</td><td>95.13</td><td>94.75</td></tr>
<tr><th>written13.txt</th><td>93.13</td><td>91.10</td><td>90.48</td></tr>
<tr><th>written17.txt</th><td>95.25</td><td>93.75</td><td>93.27</td></tr>
<tr><th>written18.txt</th><td>93.50</td><td>92.29</td><td>91.93</td></tr>
<tr><th>AVG</th><td>92.65</td><td>91.57</td><td>91.23</td></tr>
</table>

예상보다 큰 폭으로 떨어지지는 않네요. 다만 평가 데이터로 잡아내지 못한 손실이 있을 수 있다는 점은 감안하셔야 할듯합니다. 

[model_xs.zip](https://github.com/bab2min/Kiwi/files/7162139/model_xs.zip)
[model_s.zip](https://github.com/bab2min/Kiwi/files/7162140/model_s.zip)

경량화된 모델 파일도 공유드리니 직접 테스트해보시면 좋을것 같습니다!

**Comment by patnh2** [comment]
@bab2min 경량화된 모델의 성능이 상당히 좋은 것 같습니다. 감사합니다!!!
