### ISSUE TITLE
linux 환경에서는 어떻게 쓰는건가요?

### ISSUE THREAD

**Issue by sogangCSmaster** [bab2min/Kiwi#5]
안녕하세요 블로그 잘 보고있는 사람입니다.

한번 kiwi 형태소분석기 사용해보려고 하는데, linux환경에서는 어떻게 사용하는건가요?

현재 제가 사용하는 OS가 UBUNTU 16.04 LTS 인데, KiwiRunLinux 폴더에 있는 파일은 비쥬얼스튜디오 프로젝트 파일인 것 같아서요...

감사합니다.

**Comment by bab2min** [comment]
Visual Studio를 사용하여 컴파일했고, 별도로 Makefile을 구성하지 않았습니다. 컴파일하셔서 사용하시려면 Makefile을 따로 만드셔야할 것 같습니다... 그게 아니라면 리눅스 x64버전으로 컴파일된 실행 파일을 사용하시면 되겠구요

**Comment by bab2min** [comment]
크로스 컴파일을 위해 CMake를 추가하였으니, 이를 통해 리눅스 및 다른 환경에서도 쉽게 컴파일 가능합니다.
