### ISSUE TITLE
Python에서는 어떻게 연동시켜야 하나요?

### ISSUE THREAD

**Issue by sangeu2000** [bab2min/Kiwi#6]
Python module로 사용 가능하게 init 파일이라던지 만들어 두신 것 같은데... kiwiPyRaw를 어떤 식으로 빌드해서 설치해야 하는지를 찾을 수가 없습니다.

**Comment by bab2min** [comment]
0.5 버전을 배포하면서 pip에도 등록하였습니다. 
pip install kiwipiepy 
로 파이썬 패키지 설치가 가능합니다.
