### ISSUE TITLE
static 빌드에 -fPIC 옵션 추가 하는 방법 문의

### ISSUE THREAD

**Issue by mrchypark** [bab2min/Kiwi#78]
안녕하세요, 좋은 패키지 개발해주셔서 감사합니다.

다름이 아니라 static 파일을 사용해서 패키지를 만들어서 사용하려고 하는데요.
현재 cmake의 빌드를 그대로 사용하면 kiwi_static.a  생성시 -fPIC 옵션을 사용하지 않는 것을 확인했습니다.

혹시 cmake 명령에서 추가하는 방법이 있는 것인지, 아니면 cmake를 수정해야 하는 것인지 문의드립니다.

**Comment by bab2min** [comment]
안녕하세요, @mrchypark 
cmake 실행시 `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` 옵션을 주시면 fPIC 옵션을 추가할 수 있습니다~
