### ISSUE TITLE
파이썬 버전에서 오류가 발생합니다.

### ISSUE THREAD

**Issue by Shin-JaeHeon** [bab2min/Kiwi#8]
## 환경
* OS : `Windows 10 1809 64bit`
* CPU : `Intel i7 7700HQ`
* Python : `Python 3.7`
## 본문 
예제와 같이 `pip3 install kiwipiepy`로 설치했고, 코드는 아래와 같습니다.
```
from kiwipiepy import Kiwi
kiwi = Kiwi()
```
![image](https://user-images.githubusercontent.com/21238436/56032844-1ad53480-5d5e-11e9-832e-e7029f7dbe01.png)

위와같은 오류가 발생하고 있습니다. 해결 방법을 알 수 있을까요?

**Comment by bab2min** [comment]
혹시 C:\Project\kiwipy-server\venv\lib\site-packages\kiwipiepy 폴더 안에 어떤 파일들이 있는지 확인해주실수 있으신가요? 그리고 설치된 Python이 32비트용인지 64비트용인지도 알려주신다면 문제 해결에 도움이 될듯합니다.

**Comment by Shin-JaeHeon** [comment]
컴퓨터에는 `Python 3.7 64bit` 및 `Python 3.7 32bit` 모두 설치하였습니다.
![image](https://user-images.githubusercontent.com/21238436/56050728-97c8d400-5d87-11e9-806a-d850a4cfbccb.png)
![image](https://user-images.githubusercontent.com/21238436/56050736-9bf4f180-5d87-11e9-830b-52befb868d4a.png)

감사합니다.

**Comment by bab2min** [comment]
확인해본 결과 pypi 배포시 python 3.6 버전의 바이너리만 포함되는 문제가 있었네요...  python 3.7 버전도 호환가능하도록 수정해서 0.6.3 버전을 업데이트했으니 0.6.1을 지우시고 새로 kiwipiepy를 설치해보시길 바랍니다.
오류 제보 감사합니다.

**Comment by Shin-JaeHeon** [comment]
감사합니다.
