### ISSUE TITLE
capi.h 파일의 날짜와 버전이 현재 릴리즈와 다릅니다.

### ISSUE THREAD

**Issue by mrchypark** [bab2min/Kiwi#85]
0.11.0 버전 릴리즈에 0.10.0 이라고 표기되어 있습니다.

**Comment by bab2min** [comment]
@mrchypark 
안녕하세요~ 현재 배포된 버전에는 다음과 같이 0.11.0으로 되어 있습니다!
https://github.com/bab2min/Kiwi/blob/44dc6269b53a633796a4d711a9621322b077696a/include/kiwi/Macro.h#L1-L10
오늘 점심 중에 최종적으로 0.11.0으로 bump up되었는데, 혹시 그 이전의 소스코드를 보고 계신지 확인 부탁드려요~

**Comment by mrchypark** [comment]
아 넵넵 이 부분이 맞습니다. :)
