### ISSUE TITLE
한글이 포함된 경로가 있는 경우 오류

### ISSUE THREAD

**Issue by nowtoday** [bab2min/Kiwi#87]
pyinstaller를 통해 컴파일시 model 파일들을 포함하도록 했는데
사용자 이름이 한글인 경우 임시 폴더에도 한글이 포함되게 되어 오류가 나서 문의드립니다...

Uncaughted c++ exception: Failed to open model file 'C:\Users\?쒖쓽??1\AppData\Local\Temp\_MEI241162\./model/extract.mdl'.Traceback (most recent call last):
.....
  File "kiwipiepy\_wrap.py", line 67, in __init__
RuntimeError: Failed to open model file 'C:\Users\한글~1\AppData\Local\Temp\_MEI241162\./model/extract.mdl'.

**Comment by bab2min** [comment]
https://github.com/bab2min/Kiwi/blob/b8b4d83e9ef9035c6052b1a90da5de5275d7d838/include/kiwi/Mmap.h#L58-L62
Mmap 생성시 `CreateFileA`를 사용하는게 원인인듯

**Comment by mrchypark** [comment]
https://learntutorials.net/ko/cplusplus/topic/496/%ED%8C%8C%EC%9D%BC-i---o

```// Open the file 'пример\foo.txt' on Windows.
std::ifstream ifs(LR"(пример\foo.txt)"); // using wide characters with raw literal```

이 부분으로 해결할 수 있는 것 같네요.

**Comment by bab2min** [comment]
@mrchypark 네 맞습니다. wide character 버전 오버로드를 사용하도록 하면 될듯한데요, 문제는 저게 Windows에서만 사용되는 비표준이라서 나머지 환경에서는 string을 이용한 UTF8로, Windows에서는 wstring을 이용한 UTF16으로 다르게 처리되도록 하는게 조금 번거로울것 같네요~

**Comment by nowtoday** [comment]
혹시나 해서 model_path.encode('cp949') 로 넣어보려고 했는데 변수 타입이 맞지 않아 안되네요 ^^;;
TypeError: argument 2 must be str or None, not bytes

str(model_path.encode('cp949')) 일 경우
RuntimeError: Failed to open model file 'b'./\xc7\xd1\xb1\xdb'/extract.mdl'.

**Comment by bab2min** [comment]
@nowtoday 네, C++내부 구현의 Windows API 관련 문제라서 c++코드 수정없이 당장 한글경로를 사용하는건 어려울거 같습니다.
다음 패치 전까지 상대경로로 사용하시거나 ansi ascii로만 구성된 경로를 이용해주셔야할 듯 합니다.
