### ISSUE TITLE
CondVowel 의 combiner.cpp에서 swich문 문의

### ISSUE THREAD

**Issue by mrchypark** [bab2min/Kiwi#89]
[combiner.cpp](https://github.com/bab2min/Kiwi/blob/main/src/Combiner.cpp#L1030)

를 보면 switch가 기본경우 없이 총 3가지 케이스만 다루고 있습니다.

반면에 CondVowel는 https://github.com/bab2min/Kiwi/blob/main/include/kiwi/Types.h#L180 에 보면
여러 가지를 다루고 있는데요.

혹시 이 부분은 어떻게 수정하면 좋을까요?

g++ 컴파일러의 -Wswitch 경고 에 대한 부분입니다.

**Comment by bab2min** [comment]
@mrchypark combiner.cpp에서는 두 가지 경우에만 대응하고 있어요. 해당 경고에 맞춰 수정하려면 switch문 제일 끝에 `default: break;` 와 같이 아무것도 안하는 default 문을 하나 추가하면 될듯하네요.

**Comment by mrchypark** [comment]
오 그렇군요! 알겠습니다. 추가해서 pr 할께요.
