### ISSUE TITLE
0.11.1 버전 모델 파일 배포 문의

### ISSUE THREAD

**Issue by mrchypark** [bab2min/Kiwi#94]
항상 감사합니다.

이번 0.11.1 버전 배포에 모델이  base만 배포 된 것을 확인하였습니다.

혹시 패치 버전에서는 더 배포하지 않으시려고 하시는 것인지 궁금합니다.

**Comment by bab2min** [comment]
@mrchypark 아, small, large 버전의 경우 CI/CD와 연동이 되어있지 않고 수작업으로 올리고 있어서 그렇습니다..ㅎㅎ
조만간 올리도록 할게요ㅎㅎ

**Comment by mrchypark** [comment]
@bab2min 아 이런 알겠습니다. ㅎㅎ 이 이슈는 종료하겠습니다.
