### ISSUE TITLE
인용문구 부호? 사용자정의사전? 어떤 문제일지...

### ISSUE THREAD

**Issue by nowtoday** [bab2min/Kiwi#97]
"윗뱃살빼기 허리살빼기만으로는 안될거 같아."

텍스트 분석 중 위와 같은 인용문구가 들어간 경우가 있었는데 결과가 이상해
제가 혹시나 잘못 적용했나 해서 배포해주신 키위형태소 분석기 GUI (v0.11.0)로 해봤는데도 약간 이상해서요...

"윗뱃/NNG + 살/NNG + 빼/VV + 기/ETN + 허리살빼기/NNG + 만/JX + 으로/JKB + 는/JX + 안/MAG + 되/VV + ᆯ/ETM + 거/NNB + 같/VA + 어/EF + ./SF
"/SS

사용자 정의 사전을 활용해야 할 문제인지 인용문구 부호문제일지 해서 문의드려봅니다...

**Comment by bab2min** [comment]
@nowtoday 제보 감사합니다. 
현재 0.11.0, 0.11.1 버전에서 특수 문자와 관련된 버그가 있는 것이 확인되었습니다. 
조만간 수정하여 업데이트하도록 하겠습니다.

**Comment by bab2min** [comment]
@nowtoday 해당 버그는 0.11.2 버전에서 수정되었습니다
